#@copyright : younis
CC=arm-none-eabi
CFLAGS=-g -mcpu=arm926ej-s
INCS=-I .
LIBS=
SRC= $(wildcard *.c)
OBJ= $(SRC:.c=.o)
As= $(wildcard *.s)
AsOBJ= $(As:.s=.o)
project_name=UART_lab


all: $(project_name).bin
	@echo "==========Build is done=========="


startup.o: startup.s
	$(CC)-as.exe $(CFLAGS) $< -o $@

%.o: %.c 		#@app w uart
	$(CC)-gcc.exe -c $(CFLAGS) $(INCS) $< -o $@

$(project_name).elf: $(OBJ) $(AsOBJ)
	$(CC)-ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(AsOBJ) -o $@

$(project_name).bin: $(project_name).elf
	 $(CC)-objcopy.exe -O binary $< $@

clean_all: 
	rm *.o *.elf *.bin 

clean: 
	rm *.elf *.bin
